# 应用服务 WEB 访问端口
server:
  port: 8080

# jwt令牌key
spring:
  mail:
    host: smtp.163.com
    username: yanqi1711@163.com
    password: DZKRNUXOVFWSCIOB
  rabbitmq:
    addresses: localhost
    username: yanqi
    password: 123456
    virtual-host: /
  security:
    filter:
      order: -100
    jwt:
      key: sonna
      expire: 7
  datasource:
    url: jdbc:mysql://localhost:3306/study
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver